import json
L=json.load(open("coverage-ledger.json"))
def ck(a,paths,inv,m,res,art=None): return {"agent_id":a,"reviewed_paths":paths,"invariant":inv,"method":m,"result":res,"artifact":art}
X="hunt-client2-w2";Y="hunt-server2-w2";B="hunt-backup-w2"
R={
"src/sync/rows.ts#fromServerRow and applyRows":("covered",[],[ck(X,["src/sync/rows.ts","src/sync/mirrorStore.ts"],"server rows applied to mirror/store reach no HTML or executable-URL sink with data another principal controls","source","Only the signed-in user's own rows (RLS+user_id); no innerHTML/eval/dangerouslySetInnerHTML sinks; React escapes text; self-injection only."),ck(X,["src/shared/stretchWeek.ts","src/shared/listItems.ts","src/shared/config.ts","src/shared/validate.ts","src/lib/data.ts","src/components/program/ExerciseLibrary.tsx","src/components/program/StretchLibrary.tsx","src/components/stretches/Stretches.tsx"],"every URL reaching an anchor after the mirror is http(s)-restricted","source","Stretch/list cleaners enforce goodUrl; fromServerRow fallbacks pass already-cleaned server JSON; cfg.ex[].url gap is self-only (covered by Card.tsx unit).")]),
"src/sync/useGoogleSignIn.ts#window.location.assign(out.url)":("covered",[],[ck(X,["src/sync/useGoogleSignIn.ts","src/sync/account.ts"],"navigation target only influenced by same-origin API","source","out.url from same-origin POST /api/auth/sign-in/social with fixed body; no scheme check (defense in depth); hostile value needs compromised API."),ck(X,["src/sync/devUser.ts","src/main.jsx"],"dev-only URL params cannot sign in or redirect a production browser","source","applyDevUserFromUrl returns unless import.meta.env.DEV.")]),
"vite.config.js#VitePWA workbox and service worker update":("covered",[],[ck(X,["vite.config.js"],"SW never caches personalized /api responses across account switch","source","Only static precache, no runtimeCaching, /api denylisted."),ck(X,["server/app.ts"],"server cache headers keep SW and shell fresh, keep API out of shared caches","source","no-cache for index.html/sw.js/manifest; immutable only for hashed assets; unmatched /api returns JSON 404.")]),
"scripts/backup-cloud-run.sh#backup job and bucket":("candidate",["backup-bucket-soft-delete-outlives-30day-erasure-promise"],[ck(B,["scripts/backup-cloud-run.sh"],"backup job SA, bucket IAM and secret binding least-privilege and private","source","objectCreator only, secretAccessor on its secret, uniform access, public-access-prevention, 30-day lifecycle."),ck(B,["backup/run.sh","backup/Dockerfile","cloudbuild-backup.yaml"],"dump does not include live session credentials","source","session/verification data excluded; tokens encrypted; owner URL full snapshot is documented purpose."),ck(B,["scripts/restore-check.sh",".gitignore",".dockerignore"],"fetch/restore-check do not leak dumps","source","backups/ ignored by git and docker; throwaway container without published port."),ck(B,["scripts/alerts-cloud-run.sh","scripts/ci-deploy-setup.sh"],"alerting/CI setup do not widen backup access","source","Only monitoring policies; deployer gets storage.admin on _cloudbuild bucket only."),ck(B,["scripts/backup-cloud-run.sh","public/privacy.html","src/components/settings/DeleteMyData.tsx","server/legal.test.ts"],"stated 30-day erasure-from-backups guarantee holds for bucket as configured","source","Lifecycle age=30 only; soft-delete not disabled so window may extend ~7 days; live policy not source-visible.")]),
"db/migrations/20261007000001_core_tables.sql#record_row_history":("covered",[],[ck(Y,["db/migrations/20261007000001_core_tables.sql","db/migrations/20261008000002_row_level_security.sql"],"record_row_history cannot write or expose another user's history","source","Trigger inserts old.user_id; app role has no grant on row_history; RLS enabled; FKs cascade."),ck(Y,["db/migrations/20261008000003_erase_and_delete_account.sql","server/commands/account.ts","server/auth.ts"],"erase/delete remove row_history, refused_writes, sessions, tokens and revoke authorization","source","erase deletes 9 tables plus refused_writes and row_history; delete cascades and removes auth rows; no cookie cache.")]),
"server/auth/betterAuth.ts#/api/auth/sign-in/social limiter and auth.verification":("candidate",["auth-verification-oauth-state-rows-never-expire"],[ck(Y,["server/app.ts","server/rateLimit.ts","server/auth/betterAuth.ts"],"anonymous sign-in bounded by app per-IP limiter before better-auth work","source","10/min/IP before toNodeHandler; better-auth internal limiter not relied on."),ck(Y,["node_modules/better-auth/dist/state.mjs","node_modules/better-auth/dist/oauth2/state.mjs","node_modules/better-auth/dist/db/internal-adapter.mjs","db/migrations/20261008000001_auth_schema.sql"],"anonymous work leaves no unbounded persistent state","source","Each sign-in/social inserts one auth.verification row with attacker-controlled callbackURL/additionalData; removed only if consumed; no sweeper in repo.")]),
"server/clientVersion.ts#clientVersionGate":("covered",[],[ck(Y,["server/clientVersion.ts","server/app.ts","server/index.ts"],"426 gate fails closed; dev bypass unusable in production","source","Missing/non-numeric -> 426 when min set; 'dev' passes only when devAuthAllowed; client-compat control not authz."),ck(Y,["scripts/deploy-cloud-run.sh","Dockerfile","vite.config.js","src/sync/transport.ts"],"deploy env does not silently drop a security setting","source","--set-env-vars replaces env and never sets MIN_CLIENT_VERSION; gate off in prod (hardening, compatibility only).")]),
}
H={X:["Add protocol check on out.url before location.assign","Apply goodUrl to cfg.ex[].url","Drop rows when cleaner returns null in rows.ts"],
Y:["SECURITY DEFINER search_path public,pg_temp","erase_my_data take users row lock","delete_my_account does not purge auth-state verification rows","MIN_CLIENT_VERSION not set by deploy script"],
B:["backup secret holds DB owner URL; use dedicated read role","re-assert bucket settings idempotently","CMEK and audit logs not configured","restore-check trusts newest name","privacy promise to re-apply deletions on restore has no tooling"]}
for u in L:
    if u["wave"]!=2: continue
    st,fps,checks=R[u["surface"]]
    u["status"]=st;u["result_fingerprints"]=fps;u["local_checks"]=checks
    u["reviewed_paths"]=sorted({p for c in checks for p in c["reviewed_paths"]})
    u["hardening"]=H[u["agent_id"]]
json.dump(L,open("coverage-ledger.json","w"),indent=1)
