import json
L=json.load(open("coverage-ledger.json"))
def ck(a,paths,inv,m,res,art=None): return {"agent_id":a,"reviewed_paths":paths,"invariant":inv,"method":m,"result":res,"artifact":art}
A="hunt-auth-w1";D="hunt-data-w1";V="hunt-avail-cloud-w1";C="hunt-client-w1";S="hunt-supply-w1"
R={
"server/app.ts#/api/auth/*":("covered",[],[ck(A,["server/auth/betterAuth.ts","server/index.ts"],"redirect_uri/callback origin fixed server-side; OAuth state session-bound, PKCE, idToken verified; no alternate login door in production","source","baseURL env-fixed; trustedOrigins single origin; better-auth 1.7.7 state/PKCE/idToken checks confirmed; email/password only with testSignIn and throws outside dev/test; Google sole provider.")]),
"server/app.ts#POST /api/*":("covered",[],[ck(A,["server/originGuard.ts","server/app.ts","server/clientVersion.ts"],"cross-site browser mutations refused","local","Real createApp on loopback in sbx: cross-origin and null Origin POST -> 403; same-host/allowed/missing Origin pass the guard (503 only because no db). SameSite=Lax and preflight-forcing header back the missing-Origin case.","agents/hunt-auth-w1/artifacts/out/check-1.txt")]),
"server/app.ts#sessionAuth":("covered",[],[ck(A,["server/auth.ts","server/index.ts","server/dev/authCheckPage.ts","src/sync/devUser.ts"],"X-Dev-User unreachable in production; session looked up per request","source","devAuthAllowed only for NODE_ENV development/test; Dockerfile and deploy script set production; no cookie cache so revocation immediate."),ck(A,["server/commands/account.ts","db/migrations/20261008000003_erase_and_delete_account.sql"],"account deletion invalidates sessions; login rotates session id","source","delete_my_account removes auth.session/account/verification/user; fresh session on OAuth callback; only residual is empty users-row re-creation race (hardening).")]),
"server/app.ts#static and SPA fallback":("covered",[],[ck(A,["server/securityHeaders.ts","server/app.ts","server/index.ts"],"Host/forwarded headers decide no absolute URL or authz identity; CSP on all non-dev responses","local","Forwarded headers feed only req.ip/req.secure. Local run: GET /dev/anything and /dev/auth return SPA index with no CSP (hardening: needs separate script sink).","agents/hunt-auth-w1/artifacts/out/check-1.txt")]),
"server/db/connection.ts#inUserTransaction":("covered",[],[ck(D,["server/auth.ts","db/migrations/20261008000002_row_level_security.sql","server/app.ts"],"all tenant queries run in inUserTransaction with transaction-local app.user_id; RLS agrees with explicit filters","source","set_config is_local; unset GUC matches no rows; policies have USING and WITH CHECK on all 9 data tables, refused_writes, users."),ck(D,["server/db/role.ts","server/db/connection.ts"],"no request path uses an RLS-bypassing client","source","Single pool; RLS not FORCEd so depends on connecting role being ironlog_app; production role not source-observable.")]),
"server/app.ts#POST /api/commands/*":("covered",[],[ck(D,["server/app.ts","server/auth.ts","server/commands/logSession.ts","server/commands/tickCard.ts","server/commands/untickCard.ts","server/commands/deleteEntry.ts","server/commands/bodyWeight.ts","server/commands/supplementDays.ts","server/commands/documents.ts","server/commands/support.ts"],"owner only from res.locals.userId; no body field supplies user_id","source","All 20 routes after sessionAuth; every select/update/insert user-scoped; RLS second layer."),ck(D,["src/shared/commands.ts","src/shared/validate.ts","src/shared/config.ts","src/shared/week.ts"],"validators cannot carry identity/key-shaping fields","source","Explicit column maps; spreads only land in caller's own jsonb. Local vitest blocked by address-space limit; source conclusion.")]),
"server/commands/importLegacy.ts#import-legacy":("covered",[],[ck(D,["server/commands/importLegacy.ts","server/commands/support.ts","server/app.ts"],"import-legacy cannot write outside tenant, overwrite, or bypass validation","source","Dispatches through allowlisted HANDLERS with session userId; any non-201 rolls back; empty-account check under user lock; 20k/4MB caps."),ck(D,["server/commands/sync.ts","server/app.ts"],"sync pull returns only caller rows","source","since/limit digit-bounded and bound as params; table names constant; all selects user_id filtered plus RLS.")]),
"server/commands/account.ts#erase-data and delete":("covered",[],[ck(D,["server/commands/account.ts","db/migrations/20261008000003_erase_and_delete_account.sql","server/app.ts"],"erase/delete act only on caller and remove every copy","source","SECURITY DEFINER fns use app.user_id only, search_path pinned; cascade and auth rows removed; exact confirm word."),ck(D,["server/commands/support.ts","server/commands/logSession.ts","server/commands/documents.ts"],"tombstones not revivable by unauthorized/stale operation","source","Unique (user_id,client_id) incl. tombstones; revive only same-owner by design.")]),
"server/app.ts#unauthenticated endpoints":("candidate",["auth-mount-unbounded-request-body","health-db-before-api-rate-limit","ratelimit-map-unbounded-fresh-keys-full-scan"],[ck(V,["server/app.ts","server/auth/betterAuth.ts","scripts/deploy-cloud-run.sh"],"every unauthenticated route has a byte bound before buffering","local","/api/auth mounted before parsers; 32 MiB JSON body accepted with +65 MB RSS; request-count limits only.","agents/hunt-avail-cloud-w1/artifacts/out/check-1.txt"),ck(V,["server/rateLimit.ts","server/app.ts"],"limiter state bounded and per-request cost constant","local","Sweep only when size>10000 and only expired keys; per-request cost grows to 1.8ms at 120k keys.","agents/hunt-avail-cloud-w1/artifacts/out/check-3.txt"),ck(V,["server/app.ts","server/auth.ts"],"anonymous requests cannot reach DB before limiter","source","GET /api/health/db registered before rateLimit(limits.api) and runs select 1."),ck(V,["server/clientErrors.ts","server/app.ts"],"client-errors scrubber bounded","local","14-21 ms per 4kB request; capped by 4kb and 20/min/IP; hardening.","agents/hunt-avail-cloud-w1/artifacts/out/check-2.txt")]),
"scripts/deploy-cloud-run.sh#deploy":("covered",[],[ck(V,["scripts/deploy-cloud-run.sh","server/index.ts","server/db/role.ts","Dockerfile","server/auth/betterAuth.ts","server/auth.ts"],"deployed env cannot disable RLS role enforcement or enable dev/test sign-in","source","NODE_ENV=production via --set-env-vars and Dockerfile; checkDbRole throws in production on superuser/BYPASSRLS/owner; createAuth throws for test sign-in outside dev/test."),ck(V,["server/db/role.ts","db/migrations/20261008000002_row_level_security.sql"],"checkDbRole detects every RLS-inapplicable condition","source","Checks superuser, BYPASSRLS, owner of log_entries; hardening: tableowner=current_user misses inherited owner membership.")]),
"scripts/ci-deploy-setup.sh#workload identity":("candidate",["ci-deployer-builds-editor-default-build-sa-escalation","ci-deployer-run-developer-backup-job-override"],[ck(V,["scripts/ci-deploy-setup.sh",".github/workflows/deploy-cloud-run.yml"],"only main-branch tokens can impersonate the deployer SA","source","Provider condition repository+refs/heads/main; binding scoped to repository; workflow job if accepts only dispatch on main or same-repo successful Tests run."),ck(V,["scripts/ci-deploy-setup.sh","scripts/deploy-cloud-run.sh","scripts/backup-cloud-run.sh","backup/run.sh","backup/Dockerfile","cloudbuild.yaml"],"deployer SA cannot read database, secrets or backups","source","Project-scoped run.developer and cloudbuild.builds.editor may exceed documented boundary; depends on GCP defaults not in repo (needs_validation).")]),
"src/store/settingsSlice.ts#readImportFile":("candidate",["excelImport.readWeeks.warm.inherited-builtin-member-write"],[ck(C,["src/lib/excelImport.ts","src/store/settingsSlice.ts"],"attacker keys from xlsx/csv/JSON never write to Object.prototype or shared builtins","local","UNSAFE_KEY covers 3 names only; warm[day] with day=hasOwnProperty writes onto shared function; sandbox set hasOwnProperty.call=true; Object.prototype not polluted.","agents/hunt-client-w1/artifacts/out/check-1.txt"),ck(C,["src/lib/export.ts","src/shared/config.ts","src/shared/week.ts","src/store/settingsSlice.ts"],"JSON path has no recursive merge driven by file keys","source","JSON.parse own __proto__ safe; normConfig spread; no deep-merge gadget.")]),
"src/components/board/Card.tsx#ex.url href":("covered",[],[ck(C,["src/shared/stretchWeek.ts","src/shared/listItems.ts","src/shared/config.ts","src/lib/data.ts"],"user URLs reaching href are http(s)-checked on all write paths","local","normConfig does not filter cfg.ex[].url; javascript: survives to href; react-dom 19 rewrites to throw stub (sandbox vitest).","agents/hunt-client-w1/artifacts/out/check-2.txt"),ck(C,["src/components/board/Card.tsx","src/components/program/ExerciseLibrary.tsx","src/components/settings/Settings.tsx","server/securityHeaders.ts"],"no HTML/eval sink and policy backs up URL check","source","No innerHTML/dangerouslySetInnerHTML; CSP script-src self blocks javascript: nav on server build; Pages build has only React's block (hardening).")]),
"src/lib/storage.ts#localStorage and github token":("covered",[],[ck(C,["src/lib/storage.ts","src/lib/github.ts","src/store/useAppStore.ts","src/lib/export.ts","src/store/settingsSlice.ts","src/shared/config.ts"],"GitHub token stays out of backups/sync and cannot be redirected","source","Own localStorage key; sent only to api.github.com/repos/<validRepo>; stripped from exports and sync."),ck(C,["src/sync/apiDb.ts","src/sync/legacyMarker.ts","src/sync/account.ts","vite.config.js"],"local data bound to owner; SW does not cache authenticated responses","source","OWNER_KEY gate and wipeForNewAccount; precache static assets only, /api denylisted.")]),
".github/workflows/screenshots.yml#pull_request":("covered",[],[ck(S,[".github/workflows/screenshots.yml"],"untrusted code does not run with write token/secrets on untrusted event","source","pull_request not _target; no secrets; fork tokens read-only by platform default; no inline expression injection."),ck(S,[".github/workflows/test.yml",".github/workflows/deploy-cloud-run.yml"],"pull_request path does not cross into deploy authority","source","deploy uses workflow_run from same-repo push on main; no artifact/cache handoff.")]),
"package.json#dependencies and Dockerfile":("covered",[],[ck(S,["package-lock.json","package.json"],"every package bound to integrity hash","source","All entries have integrity; only non-npm URL is xlsx tarball with sha512."),ck(S,["Dockerfile",".dockerignore","scripts/build-server.mjs"],"image build takes no unreviewed mutable inputs and leaks no secrets","source","Floating node:22-slim tag (hardening); runtime copies dist only, USER node; .dockerignore excludes .env*.")]),
}
H={"hunt-auth-w1":["Gate CSP skip to /dev/auth in development only","Require Origin when session cookie present","ensure_user race recreate empty users row","better-auth default XFF ip source"],
"hunt-data-w1":["erase/delete do not take users row lock","commands carry no data_epoch","normConfigDoc spreads unknown keys"],
"hunt-supply-w1":["pin actions by SHA","persist-credentials false in screenshots.yml","base image digest"],
"hunt-client-w1":["normConfig does not apply goodUrl to cfg.ex[].url or backup.last.url","gh token key not cleared on account change","applyImport cfg[k]=v with __proto__","Pages build lacks CSP"],
"hunt-avail-cloud-w1":["slice before mask in clientErrors","provider update-oidc and repository_id binding","pin deploy-job actions","role.ts pg_has_role","--set-env-vars drops MIN_CLIENT_VERSION","two pg pools","BACKUP_BUCKET encoding"]}
for u in L:
    st,fps,checks=R[u["surface"]]
    u["status"]=st; u["result_fingerprints"]=fps; u["local_checks"]=checks
    u["reviewed_paths"]=sorted({p for c in checks for p in c["reviewed_paths"]})
    u["hardening"]=H[u["agent_id"]]
json.dump(L,open("coverage-ledger.json","w"),indent=1)
