import json
L=json.load(open("coverage-ledger.json"))
def ck(a,paths,inv,m,res,art=None): return {"agent_id":a,"reviewed_paths":paths,"invariant":inv,"method":m,"result":res,"artifact":art}
Z="hunt-client3-w3";Q="hunt-quota-w3"
R={
"src/lib/export.ts#buildCsv and workbook builders (CSV/Excel export)":("candidate",["export.buildCsv.csv-formula-injection-unneutralised-cells"],[ck(Z,["src/lib/export.ts","src/shared/validate.ts","src/store/useAppStore.ts"],"user strings in CSV do not begin with a formula trigger","local","csvCell quotes only for , \" CR LF; imported note/name starting '=' emitted as leading-= cells; XLSX builders store strings as t:'s'.","agents/hunt-client3-w3/artifacts/out/check-2.txt"),ck(Z,["src/lib/export.ts","src/components/settings/ExportUpload.tsx"],"export contains only signed-in user's own snapshot","source","Builders use in-memory snapshot; data-file export clones cfg incl. ghBackup (own data).")]),
"src/sync/apiDb.ts and outbox.ts (client sync engine)":("candidate",["sync.apiDb.gate-verified-latch-cross-account-mixing"],[ck(Z,["src/sync/apiDb.ts","src/sync/browser.ts","src/sync/transport.ts","src/sync/pull.ts","src/sync/mirrorStore.ts","src/sync/outbox.ts","src/store/useAppStore.ts"],"nothing pulled/sent unless session identity equals device owner","local","gate() latches verified=true; fake-server harness: ann tab sent ann-private entry to bob's server and pulled bob's week row; state idle, never paused account.","agents/hunt-client3-w3/artifacts/out/check-1.txt"),ck(Z,["src/sync/apiDb.ts","src/sync/mirrorStore.ts","src/sync/pull.ts"],"data epoch change invalidates mirror before use","source","pull compares epoch each page and resets store; no violation."),ck(Z,["src/sync/outbox.ts","src/sync/apiDb.ts"],"quarantined/pending docs bound to writing account","source","Binding is OWNER_KEY check in gate() plus wipe; only gap is the verified latch.")]),
"server/app.ts#authenticated write endpoints per-user quota":("candidate",["per-user-unbounded-storage-row-history-refused-writes-no-retention","import-legacy-20k-command-single-transaction-pins-shared-pool-connection"],[ck(Q,["server/app.ts","server/rateLimit.ts","server/auth.ts"],"per-user quotas keyed on authenticated id and counted across all write paths","source","byUser key from session; request-count only; no byte/row/work accounting."),ck(Q,["server/commands/documents.ts","server/commands/logSession.ts","server/commands/support.ts","db/migrations/20261007000001_core_tables.sql","db/migrations/20261007000006_library_items.sql","db/migrations/20261008000003_erase_and_delete_account.sql"],"per-user persistent storage bounded","source","No row/byte bound or retention for log_entries, library_items, list_items, row_history, refused_writes."),ck(Q,["src/shared/commands.ts","src/shared/config.ts","src/shared/validate.ts"],"validators keep stored doc well below body limit","local","validateSaveConfig kept 100816 of 100868 bytes; distinct payloads accepted.","agents/hunt-quota-w3/artifacts/out/check-1.txt"),ck(Q,["server/commands/importLegacy.ts","server/db/connection.ts","server/app.ts"],"one import-legacy request bounded in DB work and hold time","source","Up to 20k commands (~100k queries) in one transaction on one pooled connection; default pool, no timeouts.")]),
}
for u in L:
    if u["wave"]!=3: continue
    st,fps,checks=R[u["surface"]]
    u["status"]=st;u["result_fingerprints"]=fps;u["local_checks"]=checks
    u["reviewed_paths"]=sorted({p for c in checks for p in c["reviewed_paths"]})
    u["hardening"]=["export gh token in data file","outbox/mirror carry no owner id"] if u["agent_id"]==Z else ["import-legacy 4mb parsed before IP limiter and sessionAuth","fixed-window 2x burst","erase/delete limiters separate"]
json.dump(L,open("coverage-ledger.json","w"),indent=1)
